on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: self-hosted
    name: Build runner
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build container image
      run: make build
    - name: Docker Login
      run: docker login --username tmnkgwa4 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Push container image
      run: make push
